####################
#MCDNDC Config File
#Config Language: 简体中文/Chinese(Simplified)
#You Can Download More Language At https://github.com/jingwenMC/MCDNDC/tree/master/langs
####################
#作者:jingwenMC
#开源许可:GPLv3
#版本:v${project.version}
####################

#Name:配置文件版本
#Note:此项用于配置文件结构版本的确认。为防止出错，请不要自行更改
#Default: 5
#Updated:v0.1.0
config_version: 5

#Name:选择语言
#Note:取决于lang.yml的设定
#Defaut: 'zh_CN'
#Updated:v1.0.0
lang: 'zh_CN'

#Name:计分板位置
#Note:计分板的显示位置,请从[SIDEBAR,BELOW_NAME,PLAYER_LIST]中填写一个
#  SIDEBAR:侧边栏
#  BELOW_NAME:名称下方(可能会与TAB插件冲突,可能需要对TAB插件进行配置,可能比较丑,不推荐)
#  PLAYER_LIST:TAB列表(可能会与TAB插件冲突,可能需要对TAB插件进行配置)
#Default: 'SIDEBAR'
#Updated:v1.0.0
scoreboard: 'SIDEBAR'

#Name:计分板更新频率
#Note:单位为tick(1/20秒)
#Default: 40
#Updated:v1.0.0
interval: 40

#Name:玩家掉线后,词条和积分的保留时间
#Note:单位为tick(1/20秒)
#Default: 1200
#Updated:v1.3.1
wait: 1200

#Name:模块列表
#Note:请按照第一次释放配置时的格式填写,避免出错
#     模块相当于官方扩展,可根据自身需求进行启用/禁用
#Default:访问https://github.com/jingwenMC/MCDNDC/blob/master/src/main/resources/config.yml
#Updated:v1.2.0
modules:
  #自动在达到一定分值时，以达到分数的玩家的ID作为词语代号,对玩家进行词语设置
  #Updated:v1.2.0
  auto_switch_from_keeper:
    #是否启用
    enabled: true
    #要求的分值
    required_score: 3
    #切换时的提示信息
    msg_switch: '&b[MCDNDC]由于达到指定分值,玩家%player新的词语来自于词语保管器.'
  #使用一个物品进行词语切换(通过玩家输入指令得到)
  #Updated:v1.2.5
  item_switch:
    #是否启用
    enabled: true
    #获取物品的指令,带"/"
    command: '/getitem'
    #执行命令所需的权限,填写none表示无需权限
    command_perm: 'none'

#Name:词库列表
#Note:请按照第一次释放配置时的格式填写,避免出错(注:可以使用/dndc words指令在游戏内编辑)
#Default:
#  - 'Word1'
#  - 'Word2'
#  - 'Word3'
#Updated:v0.1.0
words:
  - 'Word1'
  - 'Word2'
  - 'Word3'