# ###################
# MCDNDC Config File
# More info is on the official wiki:[Work In Progress]
# ###################
lang: zh_CN
word_provider: TAB
words:
  - 'words.yml'
extension:
  internal_itemswitch:
    enable: true
    command: /getitem
    command_perm: none
  internal_scoreboard:
    enable: true
    method: SIDEBAR
    interval: 20
    add_score_on_switch: true
config_version: 1A