# ###################
# MCDNDC Config File
# More info is on the official wiki:[Work In Progress]
# ###################
lang: zh_CN
word_provider: TAB
words:
  - 'words.yml'
extension:
  internal_itemswitch:
    enable: true
    command: /getitem
    command_perm: none
config_version: 1A