name: MCDNDC
version: ${project.version}
main: top.jingwenmc.mcdndc.main
api-version: '1.13'
depend: [TAB]
authors: [jingwenMC]
description: MinecraftDoNotDoChallange
website: jingwenmc.top
commands:
  dndc:
    description: Main Command Of MCDNDC
    aliases: [dnd,byz,mcdndc]
    usage: /dndc help
permissions:
  dndc.restart:
    description: Restart Game
    default: op
  dndc.reload:
    description: Reload Config
    default: op
  dndc.play:
    description: Play MCDNDC
    default: true
  dndc.set:
    description: Set Score
    default: op