name: MCDNDC
version: ${project.version}
main: top.jingwenmc.mcdndc.main
api-version: '1.13'
depend: [TAB]
authors: [jingwenMC]
description: MinecraftDoNotDoChallange
website: jingwenmc.top
commands:
  dndc:
    description: Main Command Of MCDNDC
    aliases: [dnd,byz]
permissions:
  dndc.reload:
    description: Reload Plugin
    default: op
  dndc.play:
    description: Play MCDNDC
    default: true